site_name: sodo-meetup
site_description: 
repo_url: https://github.com/piomin/sodo-meetup
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - sodo-meetup Documentation: index.md