apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sodo-meetup
build:
  artifacts:
    - image: piomin/sodo-meetup
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}