apiVersion: apps/v1
kind: Deployment
metadata:
  name: sodo-meetup
spec:
  selector:
    matchLabels:
      app: sodo-meetup
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: sodo-meetup
    spec:
      containers:
        - name: sodo-meetup
          image: piomin/sodo-meetup
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sodo-meetup
spec:
  type: NodePort
  selector:
    app: sodo-meetup
  ports:
    - port: 8080
      nodePort: 30000